"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.BluePrintType = void 0);
const puerts_1 = require("puerts"),
  UE = require("ue"),
  ModLanguage_1 = require("./ModLanguage");

class BluePrintType extends ModLanguage_1.ModLanguage {
  static translate = [
    {
      BluePrint: "Treasure001",
      en: "Basic Supply Chest",
      chs: "简易物资箱",
      ja: "Basic Supply Chest",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure002",
      en: "Basic Supply Chest",
      chs: "简易物资箱",
      ja: "Basic Supply Chest",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure003",
      en: "Basic Supply Chest",
      chs: "简易物资箱",
      ja: "Treasure00",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure004",
      en: "Standard Supply Chest",
      chs: "标准物资箱",
      ja: "Standard Supply Chest",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure005",
      en: "Blue Tidal Heritage",
      chs: "标准物资箱_黑石增生",
      ja: "Treasure005",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure006",
      en: "Standard Supply Chest",
      chs: "标准物资箱",
      ja: "Standard Supply Chest",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure007",
      en: "Treasure007",
      chs: "标准物资箱_黑石增生",
      ja: "Treasure007",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure008",
      en: "Purple Tidal Heritage",
      chs: "豪华物资箱_黑石增生",
      ja: "Purple Tidal Heritage",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure009",
      en: "Purple Tidal Heritage",
      chs: "豪华物资箱_黑石增生",
      ja: "Treasure009",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure009",
      en: "Treasure009",
      chs: "豪华物资箱_黑石增生",
      ja: "Treasure009",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure010",
      en: "Suspicious Chest",
      chs: "丰厚物资箱",
      ja: "Treasure010",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure011",
      en: "Golden Tidal Heritage",
      chs: "幻象宝箱_金",
      ja: "Treasure011",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure012",
      en: "Treasure012",
      chs: "丰厚物资箱",
      ja: "Treasure012",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure013",
      en: "Basic Supply Chest",
      chs: "丰厚物资箱",
      ja: "Treasure013",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure014",
      en: "Standard Supply Chest",
      chs: "标准物资箱",
      ja: "Treasure014",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure015",
      en: "Advanced Supply Chest",
      chs: "丰厚物资箱",
      ja: "Treasure015",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure016",
      en: "Premium Supply Chest",
      chs: "豪华物资箱",
      ja: "Treasure016",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure017",
      en: "Treasure017",
      chs: "散落的物资箱",
      ja: "Treasure017",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure018",
      en: "Treasure018",
      chs: "标准物资箱",
      ja: "Treasure018",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure019",
      en: "Treasure019",
      chs: "简易物资箱",
      ja: "Treasure019",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure020",
      en: "Treasure020",
      chs: "丰厚物资箱",
      ja: "Treasure020",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure021",
      en: "Treasure021",
      chs: "豪华物资箱",
      ja: "Treasure021",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect001",
      en: "Lotus Seeds",
      chs: "睡莲",
      ja: "Collect001",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect002",
      en: "Ficus Microcarpa",
      chs: "薜荔",
      ja: "Collect002",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect003",
      en: "Iris",
      chs: "鸢尾花",
      ja: "Collect003",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect004",
      en: "Mushroom",
      chs: "秽炎菇",
      ja: "Collect004",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect005",
      en: "Lanternberry",
      chs: "灯笼果",
      ja: "Collect005",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect006",
      en: "Goldenrod",
      chs: "洋金凤",
      ja: "Collect006",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect007",
      en: "Red Poppy",
      chs: "虞美人",
      ja: "Collect007",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect008",
      en: "Coriolus",
      chs: "云芝",
      ja: "Collect008",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect009",
      en: "Wintry Bell",
      chs: "傲寒钟",
      ja: "Collect009",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect010",
      en: "Purple Coral Tree",
      chs: "紫珊瑚树",
      ja: "Collect010",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect011",
      en: "Golden Berry",
      chs: "金铃子",
      ja: "Collect011",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect101",
      en: "Pearl Leaf",
      chs: "珍珠草",
      ja: "Collect101",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect102",
      en: "Dewvetch",
      chs: "云露",
      ja: "Collect102",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect103",
      en: "Noctemint",
      chs: "夜息香",
      ja: "Collect103",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect104",
      en: "Honeysuckle",
      chs: "凌冬花",
      ja: "Collect104",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect105",
      en: "Perilla",
      chs: "香苏",
      ja: "Collect105",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect106",
      en: "Angelica",
      chs: "清芬草",
      ja: "Collect106",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect107",
      en: "Lemongrass",
      chs: "香柠草",
      ja: "Collect107",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect108",
      en: "Rotten Bone Orchid",
      chs: "腐骨幽兰",
      ja: "Collect108",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect109",
      en: "Crystallized Leaf",
      chs: "水灯花",
      ja: "Collect109",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect110",
      en: "Bunnywort",
      chs: "月藻",
      ja: "Collect110",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect111",
      en: "Caltrop",
      chs: "白花菱",
      ja: "Collect111",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect112",
      en: "Chromeshell",
      chs: "锦色贝",
      ja: "Collect112",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect113",
      en: "Dripsnail",
      chs: "雨声蜗",
      ja: "Collect113",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect114",
      en: "Viola",
      chs: "靛色堇",
      ja: "Collect114",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect115",
      en: "Cliffrecluse",
      chs: "崖仙子",
      ja: "Collect115",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect116",
      en: "Umbragricus",
      chs: "伞下客",
      ja: "Collect116",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect117",
      en: "Gemberry",
      chs: "龙衔珠",
      ja: "Collect117",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect118",
      en: "Edodes",
      chs: "花蕈",
      ja: "Collect118",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect119",
      en: "Hidden Fire Shedding",
      chs: "隐火蜕",
      ja: "Collect119",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect503",
      en: "Indigoite",
      chs: "萤耀晶簇",
      ja: "Collect503",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect504",
      en: "Floramber",
      chs: "植珀",
      ja: "Collect504",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect601",
      en: "Bird Egg",
      chs: "鸟蛋",
      ja: "Collect601",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect601_1",
      en: "Bird Egg Nest",
      chs: "鸟蛋_底座",
      ja: "Collect601_1",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect602",
      en: "Raw Meat",
      chs: "兽肉",
      ja: "Raw Meat",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal001",
      en: "Purple-beaked Pigeon",
      chs: "紫喙鸽",
      ja: "Animal001",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal002",
      en: "Green Pigeon",
      chs: "青翎鸽",
      ja: "Animal002",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal003",
      en: "Blue-Crowned Pigeon",
      chs: "蓝冠鸽",
      ja: "Animal003",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal004",
      en: "Grey-Crowned Gull",
      chs: "灰冠鸥",
      ja: "Animal004",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal005",
      en: "Barefoot Goose",
      chs: "赤脚雁",
      ja: "Animal005",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal006",
      en: "Snow Crane",
      chs: "雪云鹤",
      ja: "Animal006",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal012",
      en: "Green Rabbit",
      chs: "青杂兔",
      ja: "Animal012",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal013",
      en: "Rockhorn Sheep",
      chs: "岩角羊",
      ja: "Animal013",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal014",
      en: "Grey Rib Cattle",
      chs: "灰脊牛",
      ja: "Animal014",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal015",
      en: "Morisui Beef",
      chs: "森栖牛",
      ja: "Animal015",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal016",
      en: "Swallowtail Butterfly",
      chs: "霄凤蝶",
      ja: "Animal016",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal017",
      en: "Red Feather Butterfly",
      chs: "赤羽蝶",
      ja: "Animal017",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal018",
      en: "Blue Feather Butterfly",
      chs: "蓝羽蝶",
      ja: "Animal018",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal019",
      en: "Leaf-Winged Lacewing",
      chs: "叶翅蛉",
      ja: "Animal019",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal020",
      en: "Golden-Ringed Dragonfly",
      chs: "金环蜓",
      ja: "Animal020",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal021",
      en: "Group Color 1",
      chs: "群彩1",
      ja: "Animal021",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal022",
      en: "Group Color 2",
      chs: "群彩2",
      ja: "Animal022",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal023",
      en: "Silver Moon",
      chs: "银月",
      ja: "Animal023",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal024",
      en: "Flame Carp",
      chs: "焰鲤",
      ja: "Animal024",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal025",
      en: "Blackthorn Ray",
      chs: "黑棘鲼",
      ja: "Animal025",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal026",
      en: "Silver-Ringed Lizard",
      chs: "银环蜥",
      ja: "Animal026",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal027",
      en: "Blue Thorn Lizard",
      chs: "蓝棘蜥",
      ja: "Animal027",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal028",
      en: "Green Bamboo Lizard",
      chs: "青竹蜥",
      ja: "Animal028",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal029",
      en: "Black-Striped Frog",
      chs: "黑纹蛙",
      ja: "Animal029",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal030",
      en: "Golden-Backed Frog",
      chs: "金背蛙",
      ja: "Animal030",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal031",
      en: "Crow",
      chs: "乌鸦",
      ja: "Animal031",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal032",
      en: "Blobfly",
      chs: "鸣素体",
      ja: "Animal032",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay003",
      en: "Fragile Rock",
      chs: "裂纹岩壁",
      ja: "Gameplay003",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay004",
      en: "Fissured Ledge",
      chs: "裂纹岩壁",
      ja: "Gameplay004",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay014",
      en: "Induction Cell",
      chs: "控物_电池",
      ja: "Gameplay014",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay015",
      en: "Cell Socket",
      chs: "控物_电池低压底座",
      ja: "Cell Socket",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay016",
      en: "Tacetite Fulminate",
      chs: "控物_爆裂鸣晶",
      ja: "Gameplay016",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay020",
      en: "Weight Block",
      chs: "控物_重力方块",
      ja: "Gameplay020",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay021",
      en: "Sonance Casket",
      chs: "声匣",
      ja: "音匣",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay022",
      en: "Road Sign",
      chs: "转子",
      ja: "Gameplay022",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay050",
      en: "Hover Target",
      chs: "打击机关",
      ja: "Gameplay050",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay055",
      en: "Hover Target",
      chs: "射击靶底座",
      ja: "Gameplay050",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay064",
      en: "Signal Console",
      chs: "信号器终端",
      ja: "Gameplay064",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay111",
      en: "Mutterfly",
      chs: "隙声蝶",
      ja: "Gameplay111",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay112",
      en: "Mutterfly Rock",
      chs: "隙声蝶底座",
      ja: "Gameplay112",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay131",
      en: "Corroder",
      chs: "黑石污染_鸣晶底座",
      ja: "Gameplay131",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay132",
      en: "Spikes",
      chs: "黑石污染_黑石锁",
      ja: "Gameplay132",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay141",
      en: "Grapple Shooter",
      chs: "钩锁机关底座",
      ja: "Gameplay141",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay145",
      en: "Sound Emulator",
      chs: "音障仪",
      ja: "Gameplay145",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay200",
      en: "Tactical Hologram: Overdash",
      chs: "全息模拟训练仪",
      ja: "Gameplay200",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay204",
      en: "Tactical Hologram: Detonate",
      chs: "息模拟训练_命中",
      ja: "Gameplay204",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay205",
      en: "Tactical Hologram: Challenge",
      chs: "全息模拟训练_战斗",
      ja: "Gameplay205",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay206",
      en: "Echo Challenge: Cruisewing",
      chs: "声骸挑战开关_游弋蝶",
      ja: "Gameplay206",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay352",
      en: "Explosive Charge",
      chs: "爆炸果",
      ja: "Gameplay352",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay372",
      en: "Key Repeater",
      chs: "脉冲装置",
      ja: "Gameplay372",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay374",
      en: "Key Repeater",
      chs: "脉冲装置_WA11",
      ja: "Gameplay374",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay376",
      en: "Key Repeater",
      chs: "脉冲装置_WAS13",
      ja: "Gameplay376",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay381",
      en: "Magnetic Cube",
      chs: "悬浮磁石",
      ja: "Gameplay015",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay525",
      en: "Flobble",
      chs: "弹跳植物",
      ja: "Gameplay525",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay537",
      en: "Small Fragile Rock",
      chs: "可破坏石块",
      ja: "Gameplay537",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay541",
      en: "Pressure Table",
      chs: "踩踏机关",
      ja: "Gameplay541",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay558",
      en: "Energy Matrix",
      chs: "全息拼图_底座",
      ja: "Gameplay537",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay604",
      en: "Mutterfly Rock",
      chs: "隙声蝶底座_任务用",
      ja: "Gameplay604",
      es: "",
      id: "",
      vi: "",
    },
  ];

  static ModTr = (string) => {
    const Find = BluePrintType.translate.find((t) => t.BluePrint == string);
    if (Find) {
      return Find[this.GetCurrLang()] || Find.BluePrint;
    } else {
      return string; // return original string if no translation found
    }
  };
}

exports.BluePrintType = BluePrintType;
