"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.BluePrintType = void 0);
const puerts_1 = require("puerts"),
  UE = require("ue"),
  ModLanguage_1 = require("./ModLanguage");

class BluePrintType extends ModLanguage_1.ModLanguage {
  static translate = [
    {
      BluePrint: "Treasure001",
      en: "Basic Supply Chest",
      chs: "简易物资箱",
      ja: "Basic Supply Chest",
      es: "Cofre de suministros básico",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure002",
      en: "Basic Supply Chest",
      chs: "简易物资箱",
      ja: "Basic Supply Chest",
      es: "Cofre de suministros básico",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure003",
      en: "Basic Supply Chest",
      chs: "简易物资箱",
      ja: "Treasure00",
      es: "Cofre de suministros básico",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure004",
      en: "Standard Supply Chest",
      chs: "标准物资箱",
      ja: "Standard Supply Chest",
      es: "Cofre de suministros estándar",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure005",
      en: "Blue Tidal Heritage",
      chs: "标准物资箱_黑石增生",
      ja: "Treasure005",
      es: "Tidal Azul",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure006",
      en: "Standard Supply Chest",
      chs: "标准物资箱",
      ja: "Standard Supply Chest",
      es: "Cofre de suministros estándar",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure007",
      en: "Treasure007",
      chs: "标准物资箱_黑石增生",
      ja: "Treasure007",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure008",
      en: "Purple Tidal Heritage",
      chs: "豪华物资箱_黑石增生",
      ja: "Purple Tidal Heritage",
      es: "Tidal Púrpura",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure009",
      en: "Purple Tidal Heritage",
      chs: "豪华物资箱_黑石增生",
      ja: "Treasure009",
      es: "Tidal Púrpura",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure009",
      en: "Treasure009",
      chs: "豪华物资箱_黑石增生",
      ja: "Treasure009",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure010",
      en: "Suspicious Chest",
      chs: "丰厚物资箱",
      ja: "Treasure010",
      es: "Cofre sospechoso",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure011",
      en: "Golden Tidal Heritage",
      chs: "幻象宝箱_金",
      ja: "Treasure011",
      es: "Tidal Dorado",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure012",
      en: "Treasure012",
      chs: "丰厚物资箱",
      ja: "Treasure012",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure013",
      en: "Basic Supply Chest",
      chs: "丰厚物资箱",
      ja: "Treasure013",
      es: "Cofre de suministros básico",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure014",
      en: "Standard Supply Chest",
      chs: "标准物资箱",
      ja: "Treasure014",
      es: "Cofre de suministros estándar",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure015",
      en: "Advanced Supply Chest",
      chs: "丰厚物资箱",
      ja: "Treasure015",
      es: "Cofre de suministros avanzado",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure016",
      en: "Premium Supply Chest",
      chs: "豪华物资箱",
      ja: "Treasure016",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure017",
      en: "Treasure017",
      chs: "散落的物资箱",
      ja: "Treasure017",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure018",
      en: "Treasure018",
      chs: "标准物资箱",
      ja: "Treasure018",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure019",
      en: "Treasure019",
      chs: "简易物资箱",
      ja: "Treasure019",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure020",
      en: "Treasure020",
      chs: "丰厚物资箱",
      ja: "Treasure020",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Treasure021",
      en: "Treasure021",
      chs: "豪华物资箱",
      ja: "Treasure021",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect001",
      en: "Lotus Seeds",
      chs: "睡莲",
      ja: "Collect001",
      es: "Semillas de loto",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect002",
      en: "Ficus Microcarpa",
      chs: "薜荔",
      ja: "Collect002",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect003",
      en: "Iris",
      chs: "鸢尾花",
      ja: "鳶尾花",
      es: "Iris",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect004",
      en: "Terraspawn Fungus",
      chs: "秽炎菇",
      ja: "黒野荒蓮",
      es: "Hongo Terraspawn",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect005",
      en: "Lanternberry",
      chs: "灯笼果",
      ja: "灯籠菓",
      es: "Lanternberry",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect006",
      en: "Pecok Flower",
      chs: "洋金凤",
      ja: "金陽鳳",
      es: "Flor de Pecok",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect007",
      en: "Belle Poppy",
      chs: "虞美人",
      ja: "妙姿花",
      es: "Bella amapola",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect008",
      en: "Coriolus",
      chs: "云芝",
      ja: "雲芝",
      es: "Coriolus",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect009",
      en: "Wintry Bell",
      chs: "傲寒钟",
      ja: "傲寒鐘",
      es: "Campana invernal",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect010",
      en: "Violet Coral",
      chs: "紫珊瑚树",
      ja: "紫珊瑚",
      es: "Coral morado",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect011",
      en: "Bittberry",
      chs: "金铃子",
      ja: "金鈴子（キンレイシ）",
      es: "Bittberry",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect101",
      en: "Pearl Leaf",
      chs: "珍珠草",
      ja: "真珠草（コミカンソウ）",
      es: "Hierba de Perla",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect102",
      en: "Dewvetch",
      chs: "云露",
      ja: "雲露（レンの）",
      es: "Yunlu",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect103",
      en: "Noctemint",
      chs: "夜息香",
      ja: "夜息草（ミント）",
      es: "Menta nocturna",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect104",
      en: "Honeysuckle",
      chs: "凌冬花",
      ja: "忍冬（スイカズラ）",
      es: "Madreselva",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect105",
      en: "Perilla",
      chs: "香苏",
      ja: "香蘇（コウソ）",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect106",
      en: "Angelica",
      chs: "清芬草",
      ja: "清芬草（セイフンソウ）",
      es: "Angélica",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect107",
      en: "Lemongrass",
      chs: "香柠草",
      ja: "レモングラス",
      es: "Hierba de limón",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect108",
      en: "Rotten Bone Orchid",
      chs: "腐骨幽兰",
      ja: "Collect108",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect109",
      en: "Crystallized Leaf",
      chs: "水灯花",
      ja: "Collect109",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect110",
      en: "Bunnywort",
      chs: "月藻",
      ja: "月藻（ウサギゴケ）",
      es: "Hierba lunar",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect111",
      en: "Caltrop",
      chs: "白花菱",
      ja: "菱実（リョウジツ）",
      es: "Castaña de agua",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect112",
      en: "Chromeshell",
      chs: "锦色贝",
      ja: "錦色貝",
      es: "Caparazón de cromo",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect113",
      en: "Dripsnail",
      chs: "雨声蜗",
      ja: "雨声蝸牛（アメカタッムリ）",
      es: "Caracol de Goteo",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect114",
      en: "Viola",
      chs: "靛色堇",
      ja: "紺菫",
      es: "Viola",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect115",
      en: "Cliffrecluse",
      chs: "崖仙子",
      ja: "崖仙子（ドッコンソウ）",
      es: "Hada del Acantilado",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect116",
      en: "Umbragricus",
      chs: "伞下客",
      ja: "傘下客",
      es: "Umbragricus",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect117",
      en: "Gemberry",
      chs: "龙衔珠",
      ja: "龍銜珠（ヤブヘビイチゴ）",
      es: "Fresa Duchesne",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect118",
      en: "Edodes",
      chs: "花蕈",
      ja: "花蕈（ハナシイタケ）",
      es: "Edodes",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect119",
      en: "Hidden Fire Shedding", // TODO: I have no idea what this is
      chs: "隐火蜕",
      ja: "Collect119",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect503",
      en: "Indigoite",
      chs: "萤耀晶簇",
      ja: "紫晶",
      es: "Fragipúrpura",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect504",
      en: "Floramber",
      chs: "植珀",
      ja: "植珀（しょくはく）",
      es: "Floramber",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect601",
      en: "Bird Egg",
      chs: "鸟蛋",
      ja: "卵",
      es: "Huevo de ave",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect601_1",
      en: "Bird Egg Nest",
      chs: "鸟蛋_底座",
      ja: "鳥の卵の巣",
      es: "Nido de Huevos de ave",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Collect602",
      en: "Raw Meat",
      chs: "兽肉",
      ja: "獣肉",
      es: "Carne cruda",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal001",
      en: "Purple-beaked Pigeon",
      chs: "紫喙鸽",
      ja: "Animal001",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal002",
      en: "Green Pigeon",
      chs: "青翎鸽",
      ja: "Animal002",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal003",
      en: "Blue-Crowned Pigeon",
      chs: "蓝冠鸽",
      ja: "Animal003",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal004",
      en: "Grey-Crowned Gull",
      chs: "灰冠鸥",
      ja: "Animal004",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal005",
      en: "Barefoot Goose",
      chs: "赤脚雁",
      ja: "Animal005",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal006",
      en: "Snow Crane",
      chs: "雪云鹤",
      ja: "Animal006",
      es: "Grulla de nieve",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal012",
      en: "Green Rabbit",
      chs: "青杂兔",
      ja: "Animal012",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal013",
      en: "Rockhorn Sheep",
      chs: "岩角羊",
      ja: "Animal013",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal014",
      en: "Grey Rib Cattle",
      chs: "灰脊牛",
      ja: "Animal014",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal015",
      en: "Morisui Beef",
      chs: "森栖牛",
      ja: "Animal015",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal016",
      en: "Phoenix Butterfly",
      chs: "霄凤蝶",
      ja: "霄鳳蝶",
      es: "Mariposa Fénix",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal017",
      en: "Red Feather Butterfly",
      chs: "赤羽蝶",
      ja: "赤羽蝶",
      es: "Mariposa de plumas rojas",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal018",
      en: "Blue Feather Butterfly",
      chs: "蓝羽蝶",
      ja: "蒼羽蝶",
      es: "Mariposa de plumas azules",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal019",
      en: "Chrysopa",
      chs: "叶翅蛉",
      ja: "Animal019",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal020",
      en: "Golden-ringed Dragonfly",
      chs: "金环蜓",
      ja: "金輪トンボ",
      es: "Libélula de anillos dorados",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal021",
      en: "Group Color 1",
      chs: "群彩1",
      ja: "カラーグループ 1",
      es: "Grupo de color 1",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal022",
      en: "Group Color 2",
      chs: "群彩2",
      ja: "カラーグループ 2",
      es: "Grupo de color 2",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal023",
      en: "Silver Moon",
      chs: "银月",
      ja: "Animal023",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal024",
      en: "Flame Carp",
      chs: "焰鲤",
      ja: "Animal024",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal025",
      en: "Blackthorn Ray",
      chs: "黑棘鲼",
      ja: "Animal025",
      es: "",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal026",
      en: "Silver-Banded Lizard",
      chs: "银环蜥",
      ja: "銀輪トカゲ",
      es: "Lagarto de bandas plateadas",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal027",
      en: "Azure Lizard",
      chs: "蓝棘蜥",
      ja: "青棘トカゲ",
      es: "Lagarto azur",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal028",
      en: "Green Pit Lizard",
      chs: "青竹蜥",
      ja: "青竹トカゲ",
      es: "Lagarto de hoyo verde",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal029",
      en: "Black-Striped Frog",
      chs: "黑纹蛙",
      ja: "黒紋蛙",
      es: "Rana de rayas negras",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal030",
      en: "Goldenback Frog",
      chs: "金背蛙",
      ja: "金背蛙",
      es: "Rana de espalda dorada",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal031",
      en: "Crow",
      chs: "乌鸦",
      ja: "カラス",
      es: "Cuervo",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Animal032",
      en: "Blobfly",
      chs: "鸣素体",
      ja: "Animal032",
      es: "Volador",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay003",
      en: "Fragile Rock",
      chs: "裂纹岩壁",
      ja: "Gameplay003",
      es: "Roca frágil",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay004",
      en: "Fissured Ledge",
      chs: "裂纹岩壁",
      ja: "Gameplay004",
      es: "Cornisa fisurada",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay014",
      en: "Induction Cell",
      chs: "控物_电池",
      ja: "Gameplay014",
      es: "Celda de inducción",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay015",
      en: "Cell Socket",
      chs: "控物_电池低压底座",
      ja: "Cell Socket",
      es: "Toma de corriente",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay016",
      en: "Tacetite Fulminate",
      chs: "控物_爆裂鸣晶",
      ja: "Gameplay016",
      es: "Tacetica Fulminada",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay020",
      en: "Weight Block",
      chs: "控物_重力方块",
      ja: "Gameplay020",
      es: "Bloque de peso",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay021",
      en: "Sonance Casket",
      chs: "声匣",
      ja: "音匣",
      es: "Caja de sonido",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay022",
      en: "Road Sign",
      chs: "转子",
      ja: "Gameplay022",
      es: "Señal de tráfico",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay050",
      en: "Hover Target",
      chs: "打击机关",
      ja: "Gameplay050",
      es: "Objetivo flotante",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay055",
      en: "Hover Target",
      chs: "射击靶底座",
      ja: "Gameplay050",
      es: "Objetivo flotante",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay064",
      en: "Signal Console",
      chs: "信号器终端",
      ja: "Gameplay064",
      es: "Consola de señal",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay111",
      en: "Mutterfly",
      chs: "隙声蝶",
      ja: "Gameplay111",
      es: "Mascuposa",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay112",
      en: "Mutterfly Rock",
      chs: "隙声蝶底座",
      ja: "Gameplay112",
      es: "Roca de mascuposa",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay131",
      en: "Corroder",
      chs: "黑石污染_鸣晶底座",
      ja: "Gameplay131",
      es: "Corroriposas",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay132",
      en: "Spikes",
      chs: "黑石污染_黑石锁",
      ja: "Gameplay132",
      es: "Espinas",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay141",
      en: "Grapple Shooter",
      chs: "钩锁机关底座",
      ja: "Gameplay141",
      es: "Lanzador de ancla",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay145",
      en: "Sound Emulator",
      chs: "音障仪",
      ja: "Gameplay145",
      es: "Emulador de Sonido",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay200",
      en: "Tactical Hologram: Overdash",
      chs: "全息模拟训练仪",
      ja: "Gameplay200",
      es: "Holograma táctico: Parkour",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay204",
      en: "Tactical Hologram: Detonate",
      chs: "息模拟训练_命中",
      ja: "Gameplay204",
      es: "Holograma táctico: Detonar",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay205",
      en: "Tactical Hologram: Challenge",
      chs: "全息模拟训练_战斗",
      ja: "Gameplay205",
      es: "Holograma táctico: Desafío",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay206",
      en: "Echo Challenge: Cruisewing",
      chs: "声骸挑战开关_游弋蝶",
      ja: "Gameplay206",
      es: "Desafío del Eco: Alitaveloz",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay352",
      en: "Explosive Charge",
      chs: "爆炸果",
      ja: "Gameplay352",
      es: "Carga explosiva",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay372",
      en: "Key Repeater",
      chs: "脉冲装置",
      ja: "Gameplay372",
      es: "Repetidor de llave",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay374",
      en: "Key Repeater",
      chs: "脉冲装置_WA11",
      ja: "Gameplay374",
      es: "Repetidor de llave",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay376",
      en: "Key Repeater",
      chs: "脉冲装置_WAS13",
      ja: "Gameplay376",
      es: "Repetidor de llave",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay381",
      en: "Magnetic Cube",
      chs: "悬浮磁石",
      ja: "Gameplay015",
      es: "Cubo magnético",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay525",
      en: "Flobble",
      chs: "弹跳植物",
      ja: "Gameplay525",
      es: "Flobble",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay537",
      en: "Small Fragile Rock",
      chs: "可破坏石块",
      ja: "Gameplay537",
      es: "Roca frágil pequeña",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay541",
      en: "Pressure Platform",
      chs: "踩踏机关",
      ja: "Gameplay541",
      es: "Plataforma de presión",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay558",
      en: "Energy Matrix",
      chs: "全息拼图_底座",
      ja: "Gameplay537",
      es: "Matriz energética",
      id: "",
      vi: "",
    },
    {
      BluePrint: "Gameplay604",
      en: "Mutterfly Rock",
      chs: "隙声蝶底座_任务用",
      ja: "Gameplay604",
      es: "Roca de mascuposa",
      id: "",
      vi: "",
    },
  ];

  /**
   * Translate a string to the current language
   * @param {string} string The string to translate
   * @returns {string} The translated string
  */
  static ModTr(string) {
    const Find = BluePrintType.translate.reduce((acc, cur) => cur.BluePrint === string ? cur : acc, {});

    if (Find) {
      return Find[this.GetCurrLang()] || Find.BluePrint;
    }

    return string; // return original string if no translation found
  };
}

exports.BluePrintType = BluePrintType;
